### ISSUE TITLE
improve graduates linking

### ISSUE THREAD

**Issue by f-hafner** [f-hafner/mag_sample#11]
- [x] 1. extend time range up to 2015
- [x] 2. compare name similarity of documents titles: https://stackoverflow.com/questions/8897593/how-to-compute-the-similarity-between-two-text-documents. idea: by definition, people that we link publish something, and this is likely related to the topic of their dissertation.
- [x] 3. condition mag sample on people at some point/at beginning of career employed in US? It is faster and likely more precise (less noise from unrelated entities). It may reduce the size of the linked sample, but we are interested in the US anyway.
- [x] 4. save training and setting files in specific folder for graduates
- [x] 5. Create benchmarking as described below
- [x] 6. keywords comparator: count number of overlaps / dummy for at least one overlap or not
- [x] 7. title comparator: larger ngrams? stemming before tfidf? -- use benchmark for intuition
- [x] 8. extend list of first papers: now those in first 7 years of publication; maximum 10
- [ ] 9. Increase sampled fields from MAG side for people whose field can fall in different major fields (biology vs chemistry)

**Comment by f-hafner** [comment]
#### suggestion for point 2:
input proquest: `("title of dissertation", )`
input mag: `("title 1", ... "title n")` for titles of first n papers written by the author. consider all doctypes, but only consider unique names (ie, ignore duplicated names from working paper and published version)

output: the similarity of the most similar pair between proquest and mag, using tfidf cosine similarity (similar to what dedupe has for `Text` fields)

Example from data:
```python
from sklearn.feature_extraction.text import TfidfVectorizer

titles = ['flight dynamics simulation modeling for hingeless and bearingless rotor helicopters', # thesis
           'effects of unsteady aerodynamics on the flight dynamics of an articulated rotor helicopter', # paper 1
          'modeling of flexible rotor blades for helicopter flight dynamics applications'] # paper 2

tfidf = TfidfVectorizer().fit_transform(titles)
pairwise_similarity = tfidf * tfidf.T
pairwise_similarity.toarray()[0]
# [1.         0.11789304 0.32551682] -> return 0.3255
```

option: add bonus if the the DocType of the most similar title is "Thesis". but not sure how much it would add. In this case, we would need to store both the year and the title together (similar to year and institutions)

question: should we benchmark the behavior for currently identified links across mag-proquest (like the one above) against the similarity of titles of a set of papers of the same author within mag? 

thoughts, @chrished ?

**Comment by chrished** [comment]
@f-hafner  This sounds very good! The benchmarking is also a good idea
