### ISSUE TITLE
Biology write links process stops: split sample automation

### ISSUE THREAD

**Issue by chrished** [f-hafner/mag_sample#19]
Biology linking stopped during the create links script, to solve we split the data into two subsamples. This works mechanically, but it seems to create a break in the linking rate.

- [x] Check what is the cause of linking rate break (compare with putting the split at different years) and check whether the selection of the highest link score is the issue.
- [x] tidy up the biology split and make the whole process automatic

**Comment by chrished** [comment]
@f-hafner found the mistake in the new scripts: advisors were only loaded if they started publishing in the sample period. This was a wrong restriction on the sql query.

Biology runs through if limiting the sample sufficiently (threshold > 0.5 and years in 90-15).

Anything we missed here?

**Comment by f-hafner** [comment]
I think that's all
