### ISSUE TITLE
understand low advisor links in some fields, and fix

### ISSUE THREAD

**Issue by f-hafner** [f-hafner/mag_sample#21]
see output/quality_linking_advisors.pdf

for instance, goid 2449294030 has the first advisor that only has an affiliation in 2009. among others, he has a science paper w/o any affiliation reported.

check some more examples of non-linked theses in these fields

**Comment by f-hafner** [comment]
this is separate from https://github.com/f-hafner/mag_sample/issues/19

**Comment by f-hafner** [comment]
We link 50-70% of advisors in biology but 80-100% in chemistry. why?

I did some checks on advisors with many students. Details are here: https://github.com/f-hafner/mag_sample/blob/main/src/dataprep/main/reports/quality_linking_advisors.Rmd

### In sum
1. we miss some advisors with 2 first names, where the first is only the initial, for instance "c channa reddy" (authorid 2263585539). these entities are not in the sample in which we search for the links because of the restriction that length(firstname) -> Can we improve the recognition of first names? 
2. some advisors are in the sample and the links should/could be found, but are not. So far I have seen different examples: (a) first name does not match exactly (ie "dan" in MAG while "daniel" in proquest). This is perhaps less relevant. (b) names match, and also the affiliation and years match *exactly*. Examples (biology): mingdaw tsai (authorid 2159629249), naba k gupta (authorid 2298396241), paul f cook (authorid 2107503814). [eric n olson (2029316736) does not match exactly].

For 2.b, I don't know why this is. I think we can break down the causes as follows:

**1. Problems in the model**
- blocking. there are some differences. predicates are `(SimplePredicate: (commonSixGram, lastname), SimplePredicate: (commonFourGram, middlename))` in biology 1990-2015. In contrast, for the settings file 1985-2022, the predicates are `(SimplePredicate: (suffixArray, lastname),)`. For chemistry, they are `(SimplePredicate: (sameSevenCharStartPredicate, lastname),)`
- logistic regression. 
- the non-linked entities are false negatives. we could fix this with higher recall. but compared to chemistry, it seems weird to have such a high false negative rate (assuming that all the advisors we do currently not find are actually in the data)

**2. Problems in the data**
- duplicates: maybe the duplicated authors in MAG confuse the clustering. -> I have no idea how we can check this. Except maybe to check that the non-linked entities have above-average number of duplicates in MAG.
- features (affiliation-years) are not stored correctly. -> In the cases I checked, they are correct.
- comparator functions are wrong. ->I think the [tests](https://github.com/f-hafner/mag_sample/blob/main/tests/test_comparator_functions.py) reject this possibility. 


**3. Other problems**
- something wrong in the training. -> compare different iterations

Note that any of these reasons should also explain why the problem does not (seem to) occur in other fields.


### Next steps
- Can we generalize thje approach for checking and apply it to other fields? Ie, get a better idea of how representative the above insights are for the data as a whole. The challenge is the manual lookup of names in the database. 
- Relatedly, summarise the learned settings for each field, ie what are the predicates, and the weights in the logistic regression. this would perhaps help understand differences across fields.
- Fix the features for the algorithm. (1) drop the "same firstname", "same lastname" requirement, particularly for advisors where we have a good feature for affiliation and year. (2) this goes a bit against the idea of dedupe, but impose restrictions on what blocking rules can be learned?

**Comment by f-hafner** [comment]
@chrished

**Comment by f-hafner** [comment]
fix first name, last name features; extend sample to length(firstname) = 1. then check again the linking rate. then will also need to adjust the gender assignment (which relies on first name at the moment)

**Comment by f-hafner** [comment]
insights after 37abbb86bb1e86b26cfbd9ddcf3fb7ed1073d550: linking rate for  biology now slightly below 75% throughout sample period--improvement of about 10 percentage points. in turn, geology lower by about 10ppt as well, particularly in later periods. To the existing training data, I added a few more.
- what is going on?
- next steps: full sweep retraining? try the other discussed approaches? ...?

**Comment by chrished** [comment]
* gender assignment when one letter first names are allowed: 
    - if the first name is really just given as the initial, then we can't do better. 
    - if the second name after initial is a first name, we can do better
    - if the first name is written out in one of the two databases, we can use that name for gender. 
* Biology higher linking rate: so the first name = one letter issue was there. (Or the new version of the features made it easier to match)
* Geology lower linking rate: is this by introducing duplicates in the db? Could we do a simple deduplication test: List MAG author with same lastname, initial and overlap in years/institution. Are they the ones that were not linked during the new iteration of geology, but were linked before?

**Comment by f-hafner** [comment]
I re-run the labelling for geology, and the linking rate is unchanged to my last comment. I also compared the dedupe predicates from this run and from the "old" one (before changing the settings and sampling). now we have `(SimplePredicate: (commonSixGram, lastname), TfidfNGramSearchPredicate: (0.6, middlename))`, before we had `(TfidfTextSearchPredicate: (0.4, lastname),)`.

Similar to what @chrished suggested, I think the change, particularly adding the people with only a firstname initial, introduces more noise. This makes it necessary to have more blocking predicates, and may lower the linking rate. So this may be more generally the trade-off we face with the proposed change--the net effect on the fraction linked is not necessarily positive. But yes, maybe we can do something to reduce the noise.

**Comment by f-hafner** [comment]
- I added @chrished's suggestions for gender in #17. 
- #25 should have fixed the low links, but let's see the results before I close

**Comment by chrished** [comment]
@f-hafner are we happy with the new results?
