### ISSUE TITLE
validate student links

### ISSUE THREAD

**Issue by f-hafner** [f-hafner/mag_sample#22]
in chemistry, most students co-author with their advisor. https://direct.mit.edu/rest/article-abstract/95/2/698/58091/Chinese-Graduate-Students-and-U-S-Scientific?redirectedFrom=fulltext

--> since we don't use co-authors/institutions of students to link, we should in chemistry find a high match rate between the institutions and co-authors/advisors at the beginning of the career.

**Comment by f-hafner** [comment]
also, since we don't use the affiliation: those who publish pre-phd should publish at their PhD institution.

**Comment by chrished** [comment]
makes sense, these are nice sanity checks
