### ISSUE TITLE
quantiles papercites: add mutiple levels of Fields (Lvl 0, 1, 2)

### ISSUE THREAD

**Issue by f-hafner** [f-hafner/mag_sample#34]
please add mutiple levels of Fields (Lvl 0, 1, 2)

**Comment by f-hafner** [comment]
level 2 is not straightforward because we have only calculated the main field of study of a paper at level 0 and 1, but not level 2 (table `PaperMainFieldsOfStudy`). I do with levels 0 and 1 for now, is that enough?

**Comment by f-hafner** [comment]
691076eaa337d4328b8376c9b627fe6ef1cb8c69 adds quantiles 0, 0.01, 0.02, ... for level 0 and 1. @chrished  if you're happy with this for now, you can close the issue.

**Comment by chrished** [comment]
yes that's good for now
