### ISSUE TITLE
improve advisor linking

### ISSUE THREAD

**Issue by f-hafner** [f-hafner/mag_sample#9]
- use comparator functions as for grants
- restrict mag sample to be linked with people at US institutions

try one field, see difference in performance, then do the rest

**Comment by chrished** [comment]
I created branch christoph/issue-9 from flavio/issue-9 and push + merge back once I have done the training + linking of advisors.

Then we can compare `advisor_links_quality_select.Rmd
`

**Comment by chrished** [comment]
During linking, I have a few cases where I think we could have an "old" advisor, i.e. they stopped publishing a few years ago and are still advising students. However, there is no affiliation overlap. Depending on the case, I labeled those mostly as "no". I give one example here:

```
firstname : robert
lastname : bell
middlename : None
year_range : (1992,)
main_us_institutions_year : ((1992, 'texas tech university'),)
all_us_institutions_year : ((1992, 'texas tech university'),)

firstname : robert
lastname : bell
middlename : r
year_range : (1959, 1981)
main_us_institutions_year : ((1959, 'temple university'), (1965, 'temple university'), (1967, 'temple university'), (1969, 'temple university'), (1970, 'temple university'), (1981, 'temple university'))
all_us_institutions_year : ((1959, 'temple university'), (1965, 'temple university'), (1967, 'temple university'), (1969, 'temple university'), (1970, 'temple university'), (1975, 'temple university'), (1981, 'temple university'))
```

Others were more compelling, e.g. one had the exact same first, middle and lastname.

**Comment by f-hafner** [comment]
yes, it's the same person. but it is the wrong entity if MAG has another enitty that captures her full career.

**Comment by chrished** [comment]
after merging main again into christoph/issue-9 the code is running and no errors so far. Will report on the linking

**Comment by chrished** [comment]
@f-hafner linking done, I just pushed the logs. Did not check in detail yet.
